import { Element } from '../types/element';

export const generateHTML = (elements: Element[]): string => {
  const generateElementHTML = (element: Element, indent = 0): string => {
    const spaces = '  '.repeat(indent);
    const attrs = Object.entries(element.attributes)
      .map(([key, value]) => `${key}="${value}"`)
      .join(' ');
    
    const styleAttr = Object.keys(element.styles).length > 0
      ? ` style="${generateInlineStyles(element)}"`
      : '';

    switch (element.type) {
      case 'input':
        return `${spaces}<input${attrs ? ' ' + attrs : ''}${styleAttr} />`;
      case 'img':
        return `${spaces}<img src="${element.attributes.src || 'placeholder.jpg'}" alt="${element.content}"${styleAttr} />`;
      default:
        return `${spaces}<${element.type}${attrs ? ' ' + attrs : ''}${styleAttr}>\n${spaces}  ${element.content}\n${spaces}</${element.type}>`;
    }
  };

  const html = elements.map(el => generateElementHTML(el)).join('\n');
  
  return `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EasyFront Generated Page</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
${html}
</body>
</html>`;
};

export const generateCSS = (elements: Element[]): string => {
  let css = `/* Generated by EasyFront */\n\n`;
  css += `body {\n  margin: 0;\n  padding: 0;\n  font-family: system-ui, -apple-system, sans-serif;\n}\n\n`;

  elements.forEach((element, index) => {
    css += `.element-${index} {\n`;
    css += `  position: absolute;\n`;
    css += `  left: ${element.position.x}px;\n`;
    css += `  top: ${element.position.y}px;\n`;
    css += `  width: ${element.size.width}px;\n`;
    css += `  height: ${element.size.height}px;\n`;
    
    Object.entries(element.styles).forEach(([key, value]) => {
      const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
      css += `  ${cssKey}: ${value};\n`;
    });
    
    css += `}\n\n`;
  });

  return css;
};

const generateInlineStyles = (element: Element): string => {
  const styles = {
    position: 'absolute',
    left: `${element.position.x}px`,
    top: `${element.position.y}px`,
    width: `${element.size.width}px`,
    height: `${element.size.height}px`,
    ...element.styles
  };

  return Object.entries(styles)
    .map(([key, value]) => {
      const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase();
      return `${cssKey}:${value}`;
    })
    .join(';');
};